---
- sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes reload=yes
- sysctl: name="net.ipv6.conf.all.forwarding" value=1 sysctl_set=yes state=present reload=yes
- sysctl: name="net.ipv6.conf.all.proxy_ndp" value=1 sysctl_set=yes state=present reload=yes
#- sysctl: name="net.ipv4.conf.all.accept_redirects" value=0 sysctl_set=yes reload=yes
#- sysctl: name="net.ipv4.conf.all.send_redirects" value=0 sysctl_set=yes state=present reload=yes

- name: Install additional packages
  package: name={{ item }} state=installed
  with_items:
    - bash-completion
    - vim
    - iptables-services
    - tcpdump
    - telnet
    - sysstat
    - nc

- name: Enable iptables state
  systemd: name=iptables enabled=yes state=started
  with_items:
  - iptables
  - ip6tables

- name: Include vars from vars/vpn_users.yml
  include_vars:  dir='vars' files_matching={{ inc_vars }}
  no_log: True

- name: Ensure vpn domain update cronjob exists
  cron:
    name: "Update afraid.org dns for vpn"
    hour: "5"
    minute: "2"
    job: "curl -q {{ domain_vpn_upd_url }} 2>&1 > /dev/null"

- name: Update afraid.org right now
  uri: url={{ domain_vpn_upd_url }} return_content=yes

#- name: Configure chronyd
#  template: src=chrony.conf.j2 dest=/etc/chrony.conf owner="root" mode="0644"
#  notify:
#    - restart chronyd
